on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited]

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        ISSUE_BODY: ${{ github.event.issue.body }}
        COMMENT_BODY: ${{ github.event.comment.body }}
      run: |
        echo "$ISSUE_BODY"
        echo "$COMMENT_BODY"
