on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited]

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_EVENT: ${{ github.event }}
      run: |
        echo "$GITHUB_EVENT"
