name: extract mention

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check for mentions
        id: check_mentions
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          echo "Checking for mentions..."
          if [[ "$COMMENT_BODY" == *"@quipper/k12-crm-opede"* ]]; then
            echo "Mention found."
            # 新しいset-output構文を使用
            echo "mention_found=true" >> $GITHUB_OUTPUT
          else
            echo "No mention found."
            # 新しいset-output構文を使用
            echo "mention_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for mentions in Issue Body
        id: check_mentions_issue
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          echo "Checking for mentions in issue body..."
          if [[ "$ISSUE_BODY" == *"@quipper/k12-crm-opede"* ]]; then
            echo "Mention found in issue body."
            # 新しいset-output構文を使用
            echo "mention_found=true" >> $GITHUB_OUTPUT
          else
            echo "No mention found in issue body."
            # 新しいset-output構文を使用
            echo "mention_found=false" >> $GITHUB_OUTPUT
          fi
